<?xml version="1.0" encoding="utf-8"?><Database Name="db_restaurant2" Class="db_restaurant2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-I9HFBOF\SQLEXPRESS;Initial Catalog=db_restaurant2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db_restaurant2ConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetUser1" Method="GetUser1">
    <ElementType Name="GetUser1Result">
      <Column Name="ID_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>